### ISSUE TITLE
use library type to correctly infer read end

### ISSUE THREAD

**Issue by piechottam** [dieterich-lab/JACUSA#13]

**Comment by piechottam** [comment]
See attached library_type.pdf for details.
For library type = unstranded or fr-firststrad we are looking at the read end to infer the RT arrest position.
BUT when we have library type = fr-secondstrand we should be looking at read start?!

Currently, JACUSA 2.x "rt-arrest" supports unstranded reads.

[library_type.pdf](https://github.com/dieterich-lab/JACUSA/files/1151314/library_type.pdf)

**Comment by CDieterich** [comment]
On a first glimpse: second strand does not make any sense in this context.
However, you would expect a coverage increase at the read ends, wouldn't you.
