### ISSUE TITLE
How do we count low quality bases and how do they influence read end?

### ISSUE THREAD

**Issue by piechottam** [dieterich-lab/JACUSA#16]
With base call quality filtering set to 20
and given the following Read:

Position:         1    2   3  4
Base calls:      A  C  G  T
Base Quality: 40 40 40 10

How are low quality base calls treated? 
And how do they influence the read end? If at all.

Could it be that low quality bases carry RT arrest information?!

**Comment by CDieterich** [comment]
Yes, indeed. We know that read quality drops with read length
and to my knowledge this is not well explored.
Afaik, iCLIP which uses read arrests does not consider base quality.
