### ISSUE TITLE
Asterisks in FILTER and INFO column of VCF output

### ISSUE THREAD

**Issue by dmacmillan** [dieterich-lab/JACUSA#18]
As the title describes, I see asterisks in the FILTER and INFO fields in the vcf output, for example:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  wgs_tumor.bam    nodups.bam
1       14574   .       A       G       .       *       *       DP:BC   5:5,0,0,0       18:4,0,14,0
1       14590   .       G       A       .       *       *       DP:BC   5:0,0,5,0       19:12,0,7,0
1       14599   .       T       A       .       B;D     *       DP:BC   7:0,0,0,7       11:4,0,0,7
1       14673   .       G       C       .       H       *       DP:BC   8:0,2,6,0       28:0,1,27,0
```

I've read the VCF file format specification and nowhere can I find what '\*' indicates in the output. I see that if FILTER is not 'PASS' then a semi-colon separated list of codes for filters that failed will be shown. Does this mean that lines with '\*' in their FILTER column failed all filters? What about the INFO column? I see asterisks all the way down the file in the INFO column.

**Comment by piechottam** [comment]
This will be fixed in the next version of JACUSA.

Here in your output:
* FILTER "\*" means PASS
* INFO "\*" should represent the missing value "."
JACUSA uses "\*" as the missing value...

Because VCF is unaware of read strand information, we were happy to use JACUSA default output (BED like) format for calling RNA editing sites.

Are their any INFO fields that you are particularly interested?

**Comment by dmacmillan** [comment]
Just fyi, the "\*" character must be escaped in github comments otherwise they italicize the enclosed characters, your above comment I believe is experiencing this issue.

Also yes some usefule INFO fields would be:
AC, AF, AN, BQ, DB, DP, MQ

You can also use SOMATIC for cancer genomics to indicate that the variant is a somatic mutation. 1000G may also be useful along with the H2 and H3 flags. Basically any flags that would help you pinpoint if a mutation is just a common SNP, or a somatic variant. Quality scores and allelic frequencies are useful for custom filtering.

I see the BC field as well is quite nice, if you could add another field that shows the qualities of each base that would be great
