### ISSUE TITLE
How do we define pseudocounts in rt-arrest?

### ISSUE THREAD

**Issue by piechottam** [dieterich-lab/JACUSA#19]
In cases where no read through or read end can be observed at a specific position we need to define pseudocount(s).

Currently, JACUSA 2.x assumes a constant pseudocount of 1 for
read through and arrest. (1 each)

Can we do better?
Considering read ends in the neighborhood of the current position?

**Comment by CDieterich** [comment]
If there are no reads, read coverage filter applies.
In any other case, I would use the BQ of existing reads similar JACUSA 1.2.0
to generate pseudocounts
