### ISSUE TITLE
How is Phasing handled?

### ISSUE THREAD

**Issue by dmacmillan** [dieterich-lab/JACUSA#21]
For example if I have the following reference sequence with two variants/mutations:

![image](https://user-images.githubusercontent.com/5533649/28733690-23b7a644-7392-11e7-8be3-2efda731575a.png)

How would this look in the VCF output? Does it matter if mutations come from the same read? I assume that the output would look like:

`1    12345    C    T    ...`
`1    12348    T    A    ...`

**Comment by dmacmillan** [comment]
Hi, I am still very much in need of an answer to this question. If mutations occur on the same read will the VCF output reflect that? I have found cases where each edit is called on it's own separate line even though in IGV I can see reads that have BOTH mutations.

**Comment by piechottam** [comment]
Hi,

The VCF output will only contain SNPs/Edits - one per line and it wil be
not reflected in VCF that mutations occur on the same read.

Best,
Michael

2017-10-06 21:54 GMT+02:00 dmacmillan <notifications@github.com>:
