### ISSUE TITLE
Homopolymer filtering

### ISSUE THREAD

**Issue by dmacmillan** [dieterich-lab/JACUSA#22]
For the Y pileup filter. The documentation states "Filter wrong variant calls in the vicinity of homopolymers. Default 7 (Y:length)". What do you mean by in the vicinity? Does that mean that the variant is embedded within a homopolymer of length at least 7 or does it mean that the variant could be outside of the homopolyer (in it's vicinity implies outside)? The length I assume is the minimum length of the homopolymer.

**Comment by dmacmillan** [comment]
Here I see these kinds of variants:

TATTGTAACTTACTACTCCG G GGAAAAAAAGAACCATTTGG
ATTGTAACTTACTACTCCGG G GAAAAAAAGAACCATTTGGA
AATTTTCAAAGACTTGGGGG A AGTGAAGGCAGAGCCTGGTG
CGTCCTCTTCATCGTCTTCC A ACCCCATGCCGAGTGCTCAG
AGACCCCCCGTCTCTCCACT C CAAAAAAGCTCAGGGCCCCT
GGCAGCAGCGTGCCATCCCC A AGCAAGCACCAGGGCCCGTG
GCAGCAGCGTGCCATCCCCA G GCAAGCACCAGGGCCCGTGT
AGGCAGGGCCTCACTGTACC T TCCCCCACAGCCACCAAGGT
GCCCAACCCCTGCCATGGGG C CGGCGCCCTGCCGTGTGCTG
CGGAGCCGTTGTAGGCTGGG A AGGGTTCCGTTCCCACAGCG
AAATGGAGGAGCTGTTTTTT C CCCACGGAGCGGCGGCCCTG
GCTCCTCAAACTCCTTTTTT C CTGTCTTTCACCCAGTTGTC
GGCAGGAGGAAGGGGCGGGG A AGGGTGTGCCGGGCATGGGG
CTCAGCTGGGGGCCTGGGGG A AGGCCCTTCTTCAGCAGAGA
GTGTCAAAAACAAAAATTGG C CAAAAAACTAGACTTCTTTT
ACTCCATCTCAAAAAAAAAA G GAAAAAAAAAAAGAATTCAA
CCCGGAGAGCCCCGGGGGGG C CGGCTCCGCGTGGGGTTCGG
CGGATCACAGCAGCAACGGG C CGGGAAGGGCGGCGCCAGAC
GATAGCGTGCTTTCTTTTTT C CCACTTCACCCTCCAGGTGT
TTAAAAATGTGTTACTAAAA T TAAACAGCTGACACTAGAAG
CCTTGAGGACACGTGACCCC A ACCCGCCCACCGCCACTATC
CGTGGGCAAGTTGCCCAGGG T TGGGGGTGCCTAGCCAGGTG
CAAGTTGCCCAGGGTGGGGG T TGCCTAGCCAGGTGCAGTCC
GCCGTTCTGCCCCCCAGGGC A ACCCCCTGTTGTAGGCACTG
GGAGCCTGGCCGCGGACCCC T TCCCACCCCTGCCTTGCCGG
TACAGTCCGGCCCGGTGGGG A AGGAGGGAGGGAAGGCAGGC
TGGCTGATGGGGCCGGGGGG G GACCCAGGGCCCTTGCAGCT
GGCTGATGGGGCCGGGGGGG A ACCCAGGGCCCTTGCAGCTG
GATGGGGCCGGGGGGGACCC A AGGGCCCTTGCAGCTGCTGT
ATGGGGCCGGGGGGGACCCA G GGGCCCTTGCAGCTGCTGTC
AGTATTACACAAAGTTATTT T TAAAAAATGTCTGTACAATC
GAGGAGACTGAGGGAGAGGG A AGGGGACAGCACGACTGAGC
TTCCGAGACATTTGCTGGGG T TGGTTTGATGGCCAAAGAAT
AAGGAGTGCGGGGGGCGGGG C CGGGGGGTCCCACAGAACCT
CTCCCTCTCTCTCCCTCCCC A ACCCTCAGAATCCAACAGCA
AACAGAACTTTTTTTTTTTT A AAAGAAATAAAGAAAACAGT
AATTCATTCAAGACAAAAAA G GAAAACAAAGACGATGGCCC
CTCTACAAAATTGAAAAAAA C CCAGCCAGGTGTGGCAGCAT
GCTAATTTTCAAATTTTTTT G GTAGAGATGGGGTCTCACTA
GACTCTGTCTCACAAAAAAA G GCTTTCAGCATTCCACTAAT
GTTGAACAAGGGAATCACAA G GAAAACGAAAATGCAAAAAC
TTGTTAACAATGCCTTTTTT C CTTCACATAAAGTAGTTGAT
AGGCAGGAGCAAGGCCTGCG A AGGGAGGAACGGGCCGCTCC
AGGAGCAAGGCCTGCGAGGG A AGGAACGGGCCGCTCCCCGC
TAATCCAAGCTGTCAAAAAA G GCCCAAAAAGAAAGCCCTTT
AATCCAAGCTGTCAAAAAAG C CCCAAAAAGAAAGCCCTTTG
CTGTCAAAAAAGCCCAAAAA G GAAAGCCCTTTGCCAGGACA
AAACAAAAACAAAAAAACAA C CAAAAAAACCCCCTGTAACT
ACAAAAAAACAACAAAAAAA C CCCCCTGTAACTAACAAAAG
CTCACGGTTGCAATCCTTGT G GTTTTATGTGTCTGGGCAGC

some of the homopolymer regions are difficult to identify, so it is hard to tell how this filter is applied. Some of the variants appear to be outside of a homopolymeric region while others appear to be embedded within.

**Comment by dmacmillan** [comment]
Hello again,

I really do need to be able to understand this parameter, as it stands I have gone through your paper and see one section that speaks about a distance `d` that is monitored and represents the distance of a putative variant from a feature such as a homopolymeric region, indel, splice sites, or start/end of reads. It is said that if this distance does not exceed the threshold then the candidate variant is considered no further. 

However, when I look at the manual I see that `B`, `S`, and `I` pileup filters have distances associated with them but the `Y` parameter for homopolymeric filtering does not. Could you please clarify how exactly a variant is considered with respect to enabling the `Y` parameter vs not. Thank you

**Comment by piechottam** [comment]
Sorry - for the late response...
The length parameter in "Y" (filtering withing  homopolymeric regions)
defines the minimal number of successive identical BASE CALLS to be called a homopolymorphic region! A homopolymorpic region is defined based on the BASE CALLS not the reference!
Variants called within those regions are filtered.
Distance is currently not considered on homopolymeric regions.

I will correct the phrasing: In the vicinity.
