### ISSUE TITLE
How can I get the files of gDNA.bam and cDNA.bam?I don't understand what it is.Sorry ,I'm just a beginner.

### ISSUE THREAD

**Issue by duanshumeng** [dieterich-lab/JACUSA#24]

**Comment by piechottam** [comment]
I am sorry, you need to be more specific.

JACCUSA input?
JACUSA takes BAM files as input (they need to be indexed).

What ist gDNA/cDNA?
If you are searching for RNA editing sites they can be identified by means of RNA-DNA-differences.
That means your data consist of genomic DNA (gDNA) and sequenced RNA which most sequencing technologies employ reverse transcription RNA -> cDNA (complementary DNA) and subsequent "cDNA" sequencing.

Sample data?
If you are looking for sample data. Let me know if you have problems accessing:
https://cloud.dieterichlab.org/index.php/s/349PMjCdJl4wUwV

**Comment by tjakobi** [comment]
Just a side note: the old cloud server (cloud.dieterichlab.org) has been retired and repurposed, the links are not working anymore and data has to be reuploaded to the new server, data.dieterichlab.org.
