### ISSUE TITLE
Jacusa command log in output file header

### ISSUE THREAD

**Issue by AMChalkie** [dieterich-lab/JACUSA#26]
Hi,

For keeping track of things it would be super to have a copy of the command line options choosen in the first line of any jacusa output file, with ##. Helps keep track of versioning, databases used, etc.

Cheers
/Alistair

**Comment by piechottam** [comment]
Hi,

you are absolutely right!

In the upcoming JACUSA 2.x there will be a header line such as the
following one:

## JACUSA2 Version: 2.0.0-BETA24 (new_lrt) call-2 -b 1.bed -a
B:distance=7,I:distance=7,S:distance=7 -c 10 -p 4 -P1 FR-SECONDSTRAND -P2
FR-SECONDSTRAND -r 2call.out.tmp [...]
#contig start   end     name    stat    strand  bases11 bases12 bases21
bases22 info    filter_info


Best,
Michael

Am Mi., 19. Sep. 2018 um 09:04 Uhr schrieb Alistair Chalk <
notifications@github.com>:

**Comment by AMChalkie** [comment]
Great. Any timeframe on a new version and/or things I should look out for. Happy to beta test.

**Comment by CDieterich** [comment]
Hi Alistair,

we can make a beta version of JACUSA2 with a similar function set as in JACUSA1 available to you. Please let us know if you are happy to help fixing some of the bugs.

All best wishes,

Christoph

**Comment by AMChalkie** [comment]
Yes happy to do so.
