### ISSUE TITLE
JACUSA running wrong

### ISSUE THREAD

**Issue by mynameliuxiang** [dieterich-lab/JACUSA#27]
Hi

I running JACUSA, but there is something wrong in logfile:
tail logfile 
[ INFO ] 02:24:00	:	 Started screening contig scaffold232081:277-4771
[ INFO ] 02:24:00	:	 Started screening contig scaffold226941:87-524
[ INFO ] 02:24:00	:	 Started screening contig scaffold222121:216-831
[ INFO ] 02:24:00	:	 Started screening contig scaffold234201:3573-10807
[ INFO ] 02:24:00	:	 Started screening contig scaffold203801:370-869
[ INFO ] 02:24:00	:	 Started screening contig scaffold236361:111-991
[ INFO ] 02:24:00	:	 Started screening contig scaffold237141:54-346
[ INFO ] 02:24:00	:	 Started screening contig scaffold220141:22-1328
[ INFO ] 02:24:00	:	 Started screening contig scaffold239001:87-462
[ INFO ] 02:24:00	:	 Started screening contig scaffold233041:28-3157
Exception in thread "Thread-9" java.lang.ArrayIndexOutOfBoundsException: 1
	at jacusa.estimate.MinkaEstimateDirMultParameters.getLogLikelihood(MinkaEstimateDirMultParameters.java:187)
	at jacusa.estimate.MinkaEstimateDirMultParameters.maximizeLogLikelihood(MinkaEstimateDirMultParameters.java:111)
	at jacusa.method.call.statistic.AbstractDirichletStatistic.estimate(AbstractDirichletStatistic.java:229)
	at jacusa.method.call.statistic.AbstractDirichletStatistic.getStatistic(AbstractDirichletStatistic.java:255)
	at jacusa.method.call.statistic.dirmult.DirichletMultinomialRobustCompoundError.getStatistic(DirichletMultinomialRobustCompoundError.java:76)
	at jacusa.method.call.statistic.AbstractDirichletStatistic.addStatistic(AbstractDirichletStatistic.java:145)
	at jacusa.pileup.worker.AbstractCallWorker.processParallelPileup(AbstractCallWorker.java:41)
	at jacusa.pileup.worker.AbstractWorker.processParallelPileupIterator(AbstractWorker.java:186)
	at jacusa.pileup.worker.AbstractWorker.run(AbstractWorker.java:67)

And result output just 9 tmp file:
*txt_9_tmp.gz

I have no idea what or how to deal with it . It will appreciate if you give some advice.

**Comment by piechottam** [comment]
Hi,
what Version of JACUSA do you use and what is the command line you used to
start JACUSA?
Best


Am Do., 27. Sep. 2018 um 09:46 Uhr schrieb mynameliuxiang <
notifications@github.com>:

**Comment by mynameliuxiang** [comment]
I use newly JACUSA_v1.2.3.jar

**Comment by piechottam** [comment]
Please provide the command line options you have used!

Am Do., 27. Sep. 2018 um 11:35 Uhr schrieb mynameliuxiang <
notifications@github.com>:

**Comment by mynameliuxiang** [comment]
I use newly JACUSA_v1.2.3.jar
and the command are:

java -jar JACUSA_v1.2.3.jar call-2 \
 -a H:2,M \
 --min-coverage1 4 \
 --min-coverage2 8 \
 --min-mapq1 20 \
 --min-mapq2 20 \
 --build-pileup RF-FIRSTSTRAND,UNSTRANDED \
 --threads 10 \
 --min-basq 25 \
 --min-basq2 25 \
 --result-file $cw/$i/$i.txt \
 $RNAbam/$i/$i.bam \
 $DNAbam

and my RNA_seq data are dUTP strand specific.

**Comment by piechottam** [comment]
Thank you.
Your command line looks good!
Unfortunately, I cannot help you without looking at the data!

What are you analyzing?

For a quick solution, I suggest removing regions that you are not
interested in!
If you are not interested in scaffolds you could remove them from
consideration!
Create a BED file (e.g.: region.bed) with the coordinates of regions that
you are interested in.

Format of region.bed:
#contig\t\start\end
1\t0\t1000
2\t0\10000
[...]

Add the following to your existing JACUSA command line:
[...] -b region.bed [...]
This should help to omit the problematic region!
Even better you could identify the problematic region and if you care,
share the problematic region to identify if we are dealing with a bug or
some other data related artifact.

Sry, but without the data, it is extremely difficult to find the cause of
the problem
because for 2.5 the computation was fine and I have never come across this
error!



Am Do., 27. Sep. 2018 um 11:38 Uhr schrieb mynameliuxiang <
notifications@github.com>:

**Comment by mynameliuxiang** [comment]
hi

It's really kind of you for reply, and I'll take a try with your advice.
Thanks

**Comment by mynameliuxiang** [comment]
Hi:

I followed your advice, using " -b cds.bed" file, and fortunately it make sense. 
There may be  something unreasonable with my bam file in non_cds region.

thanks for you advice!

**Comment by piechottam** [comment]
Great!
If you have time to share your data
or
once you publish your data, please let me know.
I would like to investigate this artifact in the non_cds region.


Am Do., 27. Sep. 2018 um 15:36 Uhr schrieb mynameliuxiang <
notifications@github.com>:

**Comment by mbnmbn00** [comment]
Hi,

I just ran into the same error.

> Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: -1
>         at jacusa.pileup.Counts.add(Counts.java:112)
>         at jacusa.pileup.DefaultPileup.flat(DefaultPileup.java:156)
>         at jacusa.method.call.statistic.dirmult.DirichletMultinomialRobustCompoundError.getStatistic(DirichletMultinomialRobustCompoundError.java:58)
>         at jacusa.method.call.statistic.AbstractDirichletStatistic.addStatistic(AbstractDirichletStatistic.java:101)
>         at jacusa.pileup.worker.AbstractCallWorker.processParallelPileup(AbstractCallWorker.java:41)
>         at jacusa.pileup.worker.AbstractWorker.processParallelPileupIterator(AbstractWorker.java:186)
>         at jacusa.pileup.worker.AbstractWorker.run(AbstractWorker.java:67)

I noticed that this occurs when reads are mapped into 'N' (gap). See the example alignment.

![image](https://user-images.githubusercontent.com/14007210/63190746-b2ec6e80-c01b-11e9-8fe4-856c038e04fa.png)

Hope it helps for future users.
