### ISSUE TITLE
Stranded data: 

### ISSUE THREAD

**Issue by rtasakis** [dieterich-lab/JACUSA#29]
Hi, 

Just writing for a definition: In the manual, you guys write:
FR-FIRSTSTRAND STRANDED library - first strand sequenced,
FR-SECONDSTRAND STRANDED library - second strand sequenced, and
UNSTRANDED UNSTRANDED library. 

So we have generated data that are sequenced with the KAPA RNA Hyperprep Kit and works like this:
1. 1st strand cDNA synthesis using random priming;
2. combined 2nd strand synthesis and A-tailing, which
converts the cDNA:RNA hybrid to double-stranded
cDNA (dscDNA), incorporates dUTP into the second
cDNA strand for stranded RNA sequencing, and adds
dAMP to the 3' ends of the resulting dscDNA;
3. adapter ligation, where dsDNA adapters with 3' dTMP
overhangs are ligated to library insert fragments; and
4. library amplification, to amplify library fragments
carrying appropriate adapter sequences at both ends
using high-fidelity, low-bias PCR. The strand marked
with dUTP is not amplified, allowing strand-specific
sequencing.

That means that the **FR-SECONDSTRAND STRANDED library - second strand sequenced** is the right option for us? In other words, this  option means that the second strand will be the identical to the RNA seq ? 

Thanks a bunch,

**Comment by piechottam** [comment]
Hi,
I dont't know this Kit.
But from your description I would have picked *FR-SECONDSTRAND. *
After mapping please check your results in IGV.

Best,
Michael
Am Di., 26. Feb. 2019 um 09:59 Uhr schrieb rtasakis <
notifications@github.com>:

**Comment by rtasakis** [comment]
Sounds about right!
Thanks a lot,
RT
