### ISSUE TITLE
sample in silico data links in "April 8th, 2019" manual not working?

### ISSUE THREAD

**Issue by pauldaly1** [dieterich-lab/JACUSA#32]
Hello,

These links such as "http://www.age.mpg.com/software/jacusa/sample_data/hg19_chr1_gDNA_VS_cDNA.tar.gz" for "hg19_chr1_gDNA_VS_cDNA.tar.gz" do not work?

Changing the .com to .de did not work.

sorry if files are available somewhere else and I have not seen. In the "Test data" issue it stated that they were updated.

regards,
Paul

**Comment by tjakobi** [comment]
Dear @pauldaly1,

these links are outdated and do not work anymore. 

Just to to be sure: are those from the JACUSA manual, i.e.: 
https://github.com/dieterich-lab/JACUSA/blob/master/manual/manual.tex

The correct and updated links are at 

https://github.com/dieterich-lab/JACUSA/blob/master/README.md

However, the tex manual should be fixed, too.

Cheers,
Tobias

**Comment by piechottam** [comment]
tex manual has been fixed
