### ISSUE TITLE
Wrong function names?

### ISSUE THREAD

**Issue by y9c** [dieterich-lab/JACUSA#40]
https://github.com/dieterich-lab/JACUSA/blob/2d93ebbbace1e8521cb067e216384be326a20b31/src/jacusa/pileup/builder/FRPairedEnd1PileupBuilderFactory.java#L5

**Comment by y9c** [comment]
FRPairedEnd1PileupBuilderFactory or RFPairedEnd1PileupBuilderFactory?

**Comment by piechottam** [comment]
Yes, wrong name.
It should read RFPairedEnd1PileupBuilderFactory.

Sry, won't be fixed - new JACUSA **2** 
just to be released.

**Comment by y9c** [comment]
Hi Michael,

When will JACUSA2 be released?

**Comment by piechottam** [comment]
Sry, for the long delay.
Hopefully this year.

**Comment by y9c** [comment]
Got it, thanks!

**Comment by y9c** [comment]
> Hopefully this year.

Any update on jacasa2?

**Comment by piechottam** [comment]
We are finalizing the manuscript.

Best,
Michael

Am 15.03.2021 08:52 schrieb Chang Y:

**Comment by y9c** [comment]
Congratulations!
